global proc FilePathLocator() {};

string $locatorInfo = `whatIs FilePathLocator`;
string $filePath = `substring $locatorInfo 25 999`;
string $pluginDir = `dirname $filePath`;

string $pythonCmd = "import sys;";
$pythonCmd += "sys.path.append('" + $pluginDir + "');";
$pythonCmd += "import Install;";
$pythonCmd += "import importlib;";
$pythonCmd += "importlib.reload(Install);";
$pythonCmd += "Install.Install()";

python($pythonCmd);